services:
  - type: web
    name: neobank-agente-corporativo
    env: python
    region: ohio
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
    startCommand: "python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false